name: blitz_desktop
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  authentication:
    path: ../../authentication
  common:
    path: ../../common
  common_blocs:
    path: ../../common_blocs
  info_screen_plus_plus:
    path: ../../fragments/info_screen_plus_plus
  list_transactions_fragment:
    path: ../../fragments/list_transactions
  settings_fragment:
    path: ../../fragments/settings
  subscription_repository:
    path: ../../subscription_repository
  big_screen:
    path: ../../fragments/big_screen
  small_screen:
    path: ../../fragments/small_screen

  flutter_bloc: ^8.1.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/

    # flags
    - assets/flags/de.png
    - assets/flags/gb.png
    - assets/flags/no.png

    # icons
    - assets/RaspiBlitz_Logo_Icon_Negative.png
    - assets/icons/link.png
    - assets/icons/lightning.png
    - assets/icons/satoshi-v2.png

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono/RobotoMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/RobotoMono/RobotoMono-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/RobotoMono/RobotoMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/RobotoMono/RobotoMono-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/RobotoMono/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoMono/RobotoMono-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/RobotoMono/RobotoMono-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/RobotoMono/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMono/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoMono/RobotoMono-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/RobotoMono/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RobotoMono/RobotoMono-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/RobotoMono/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoMono/RobotoMono-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Eczar
      fonts:
        - asset: assets/fonts/eczar/Eczar-Bold.ttf
          weight: 700
        - asset: assets/fonts/eczar/Eczar-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/eczar/Eczar-Medium.ttf
          weight: 500
        - asset: assets/fonts/eczar/Eczar-Regular.ttf
          weight: 400
        - asset: assets/fonts/eczar/Eczar-SemiBold.ttf
          weight: 600
