name: graph_network_canvas
description: GraphNetwork Canvas is a interactive library that enables visualization and analysis of graph networks through customizable nodes and edges.
version: 0.5.1
homepage: https://github.com/fusion44/blitz_gui

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
