name: regtest_headless
description: A sample command-line application.
version: 0.5.1
publish_to: none

environment:
  sdk: '>=2.19.3 <3.0.0'


dependencies:
  dio: ^4.0.6
  path: ^1.8.3

  # locals
  regtest_core: ^0.5.1
  blitz_api_client: ^0.5.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
