name: regtest_core
description: A shared core library between the regtest gui and headless tester
version: 0.5.1
publish_to: 'none' 

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  dio: ^4.0.6
  english_words: ^4.0.0
  intl: ^0.18.0
  meta: ^1.9.1

  # local
  common: ^0.5.1
  blitz_api_client: ^0.5.1
  bloc: ^8.1.2
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
