name: info_screen_plus_plus
description: Next generation info screen for the Raspiblitz
version: 0.5.1
publish_to: "none"

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  timeago: ^3.3.0
  flutter_spinkit: ^5.1.0
  material_design_icons_flutter: ^6.0.7096
  flutter_layout_grid: ^2.0.1
  intl: ^0.18.0

  # locals
  authentication: ^0.5.1
  common: ^0.5.1
  common_blocs: ^0.5.1
  common_widgets: ^0.5.1
  subscription_repository: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
