name: authentication
description: Blitz GUI authentication package
publish_to: "none"

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  formz: ^0.4.1
  equatable: ^2.0.5

  common:
    path: ../common
  flutter_login_lite:
    path: ../flutter_login_lite

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - ../../assets/RaspiBlitz_Logo_Icon_Negative.png
