name: big_screen
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  go_router: ^4.4.1
  dropdown_button2: ^1.8.0
  flutter_bloc: ^8.1.1

  authentication:
    path: ../../authentication
  common:
    path: ../../common
  common_blocs:
    path: ../../common_blocs
  list_transactions_fragment:
    path: ../list_transactions
  settings_fragment:
    path: ../settings
  subscription_repository:
    path: ../../subscription_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - ../../../assets/RaspiBlitz_Logo_Icon_Negative.png
