name: classic_info_screen
description: A Widget to mimic the aesthetic of the classic RaspiBlitz command line overview screen.
version: 0.5.1
publish_to: "none"

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_bloc: ^8.1.2
  intl: ^0.17.0

  # locals
  authentication: ^0.5.1
  common: ^0.5.1
  common_widgets: ^0.5.1
  common_blocs: ^0.5.1
  subscription_repository: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
