name: list_transactions_fragment
description: A fragment that lists transactions
publish_to: "none"

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  bloc_concurrency: ^0.2.0
  freezed_annotation: ^2.0.3
  flutter_staggered_animations: ^1.0.0
  intl: ^0.17.0
  
  authentication:
    path: ../../authentication
  common:
    path: ../../common
  common_blocs:
    path: ../../common_blocs
  subscription_repository:
    path: ../../subscription_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.0.3+1
  build_runner: ^2.1.7
