name: settings_fragment
description: A fragment that handles settings for the app
version: 0.5.1
publish_to: "none"

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.1
  hive_flutter: ^2.0.0-dev
  intl: ^0.17.0

  # locals
  common: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
