name: small_screen
description: A new Flutter package project.
version: 0.5.1
publish_to: "none"

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  go_router: ^6.0.6
  qr_flutter: ^4.0.0
  flutter_bloc: ^8.1.2
  flutter_translate: ^4.0.2

  # locals
  authentication: ^0.5.1
  common: ^0.5.1
  common_blocs: ^0.5.1
  common_widgets: ^0.5.1
  custom_keyboard: ^0.5.1
  info_screen_plus_plus: ^0.5.1
  list_transactions_fragment: ^0.5.1
  settings_fragment: ^0.5.1
  subscription_repository: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
