name: setup_app
description: A Desktop application to help creating an SD card for the RaspiBlitz project.
publish_to: "none"
version: 0.5.1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  material_design_icons_flutter: ^6.0.7096
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  validators: ^3.0.0
  flutter_spinkit: ^5.1.0
  equatable: ^2.0.5
  flutter_translate: ^4.0.2
  flutter_breadcrumb: ^1.0.1
  flutter_staggered_animations: ^1.1.1
  go_router: ^6.0.6
  dio: ^4.0.6
  bitsdojo_window: ^0.1.5
  lan_scanner: ^3.5.0
  network_info_plus: ^3.0.2
  cupertino_icons: ^1.0.5
  http: ^0.13.5

  # locals
  common: ^0.5.1
  common_widgets: ^0.5.1
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/

    # flags
    - assets/flags/de.png
    - assets/flags/gb.png
    - assets/flags/no.png

    # icons
    - assets/RaspiBlitz_Logo_Icon_Negative.png
    - assets/icons/link.png
    - assets/icons/lightning.png
    - assets/icons/satoshi-v2.png

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono/RobotoMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/RobotoMono/RobotoMono-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/RobotoMono/RobotoMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/RobotoMono/RobotoMono-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/RobotoMono/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoMono/RobotoMono-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/RobotoMono/RobotoMono-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/RobotoMono/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMono/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoMono/RobotoMono-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/RobotoMono/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RobotoMono/RobotoMono-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/RobotoMono/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoMono/RobotoMono-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Eczar
      fonts:
        - asset: assets/fonts/eczar/Eczar-Bold.ttf
          weight: 700
        - asset: assets/fonts/eczar/Eczar-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/eczar/Eczar-Medium.ttf
          weight: 500
        - asset: assets/fonts/eczar/Eczar-Regular.ttf
          weight: 400
        - asset: assets/fonts/eczar/Eczar-SemiBold.ttf
          weight: 600

import_sorter:
  comments: false
