name: regtest_core
description: A shared core library between the regtest gui and headless tester
version: 1.0.0

publish_to: 'none' 

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  dio: ^4.0.6
  english_words: ^4.0.0
  intl: ^0.17.0
  blitz_api_client:
    path: ../../../../../blitz_api_client_libraries/clients/dart-dio
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
