name: list_transactions_fragment
description: A fragment that lists transactions
version: 0.5.1
publish_to: "none"

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.1
  freezed_annotation: ^2.2.0
  flutter_staggered_animations: ^1.1.1
  intl: ^0.17.0

  authentication: ^0.5.1
  common: ^0.5.1
  common_blocs: ^0.5.1
  subscription_repository: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.0.3+1
  build_runner: ^2.1.7
