name: common_blocs
description: Blitz GUI package which contains all less specialized Blocs that can be used in many places.
publish_to: "None"

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.0

  authentication:
    path: ../authentication
  common:
    path: ../common
  subscription_repository:
    path: ../subscription_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
