name: pi_deploy
description: An application to push code the GUI app to a Raspbee PI
version: 0.5.1
publish_to: none

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  dart_console: ^1.0.2
  watcher: ^1.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
