name: regtest_headless
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.3 <3.0.0'


dependencies:
  regtest_gui:
    path: ../gui
  blitz_api_client:
    path: ../../../../../blitz_api_client_libraries/clients/dart-dio
  regtest_core:
    path: ../core
  dio: ^4.0.6
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
