name: flutter_login_lite
description: A login widget with simple login functionalities (based on https://github.com/NearHuscarl/flutter_login)
publish_to: "none"

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  another_transformer_page_view: ^2.0.1
  another_flushbar: ^1.12.29
  flutter_signin_button: ^2.0.0
  quiver: ^3.2.1
  url_launcher: ^6.1.9
  
  common:
    path: ../common
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
